# Generated by Django 5.2 on 2025-04-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='points_rewarded',
            field=models.IntegerField(default=10),
        ),
    ]
