# Generated by Django 5.2 on 2025-04-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_points_rewarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='points_processed',
            field=models.BooleanField(default=False),
        ),
    ]
