# Generated by Django 5.2 on 2025-04-24 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_points_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='points_rewarded',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
