# Generated by Django 5.2 on 2025-04-26 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
        ('tasks', '0004_alter_task_points_rewarded'),
    ]

    operations = [
    ]
