# Generated by Django 5.2 on 2025-04-16 15:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wearable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('last_synced', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wearables', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('steps', models.IntegerField(default=0)),
                ('heart_rate', models.IntegerField(null=True)),
                ('calories', models.IntegerField(default=0)),
                ('sleep_hours', models.FloatField(null=True)),
                ('wearable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_data', to='wearables.wearable')),
            ],
            options={
                'unique_together': {('wearable', 'date')},
            },
        ),
    ]
