# Generated by Django 5.2 on 2025-04-26 11:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='calories',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='heart_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='sleep_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wearable',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wearable',
            name='provider',
            field=models.CharField(choices=[('google', 'Google Fit'), ('apple', 'Apple Health')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='wearable',
            unique_together={('user', 'provider')},
        ),
    ]
