# Generated by Django 5.2 on 2025-04-27 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_post_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
