# Generated by Django 5.2 on 2025-04-22 18:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SustainabilityAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('points_earned', models.IntegerField(default=0)),
            ],
        ),
    ]
