# Generated by Django 5.2 on 2025-04-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sustainabilityaction',
            name='point_procceded',
            field=models.BooleanField(default=False),
        ),
    ]
