# Generated by Django 5.2 on 2025-04-24 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainability', '0002_sustainabilityaction_point_procceded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sustainabilityaction',
            old_name='point_procceded',
            new_name='points_processed',
        ),
    ]
