# Generated by Django 5.2 on 2025-04-24 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainability', '0003_rename_point_procceded_sustainabilityaction_points_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sustainabilityaction',
            name='points_earned',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
