# Generated by Django 5.2 on 2025-04-26 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_points'),
        ('users', '0002_user_avatar_user_bio_user_followers'),
    ]

    operations = [
    ]
