# Generated by Django 5.2 on 2025-04-26 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20250426_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
    ]
